### ISSUE TITLE
rgroupCSSseparator argument already has default value

### ISSUE THREAD

**Issue by Chris-M-P** [dkilfoyle/Table1#6]
This shiny app doesn't seem to be compatible with the newest version of Gmisc (v 1.0.1). The `rgroupCSSseparator` argument now has a default value. I'm getting this error message when I run an example using the melanoma dataset:
`You have set both the old parameter name: 'rgroupCSSseparator' and the new parameter name: 'css.rgroup.sep'.`

This is addressed here http://gforge.se/2014/07/fast-track-publishing-using-rmarkdown/#comment-404799

**Comment by dkilfoyle** [comment]
Thanks. Yes, new version of GMisc and htmlTable have renamed some variables. Should work now.
